In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras import Sequential

In [2]:
df=pd.read_csv('goog1.csv')
df

Date        Open        High         Low       Close   Volume
0   12/19/2016  790.219971  797.659973  786.270020  794.200012  1225900
1   12/20/2016  796.760010  798.650024  793.270020  796.419983   925100
2   12/21/2016  795.840027  796.676025  787.099976  794.559998  1208700
3   12/22/2016  792.359985  793.320007  788.580017  791.260010   969100
4   12/23/2016  790.900024  792.739990  787.280029  789.909973   623400
..         ...         ...         ...         ...         ...      ...
56   3/13/2017  844.000000  848.684998  843.250000  845.539978  1149500
57   3/14/2017  843.640015  847.239990  840.799988  845.619995   779900
58   3/15/2017  847.590027  848.630005  840.770020  847.200012  1379600
59   3/16/2017  849.030029  850.849976  846.130005  848.780029   970400
60   3/17/2017  851.609985  853.400024  847.109985  852.119995  1712300

[61 rows x 6 columns]

In [3]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()

In [4]:
closed=scaler.fit_transform(df['Close'].values.reshape(-1,1))
closed

array([[0.27870496],
       [0.30635093],
       [0.28318798],
       [0.24209223],
       [0.22527981],
       [0.24570341],
       [0.16475695],
       [0.13661236],
       [0.        ],
       [0.17833138],
       [0.18779601],
       [0.27646347],
       [0.42752207],
       [0.43374872],
       [0.41058501],
       [0.44943925],
       [0.43013678],
       [0.44906604],
       [0.4083435 ],
       [0.42652559],
       [0.37801975],
       [0.41344979],
       [0.5914072 ],
       [0.64819422],
       [0.79514303],
       [0.75130792],
       [0.64122041],
       [0.37982571],
       [0.31095859],
       [0.29732258],
       [0.33262797],
       [0.36948926],
       [0.36762172],
       [0.43773312],
       [0.4552927 ],
       [0.4699875 ],
       [0.52117039],
       [0.59053537],
       [0.60560414],
       [0.58729739],
       [0.6518054 ],
       [0.70049824],
       [0.74520517],
       [0.73399766],
       [0.74109613],
       [0.70759672],
       [0.71556701],
       [0.639

In [ ]:
train_data=closed[:int(len(closed)*0.8)]
train_data.shape

In [ ]:
test_data=closed[int(len(closed)*0.8):]
test_data.shape

In [7]:
def creat_seq(data,time=6):
    x=[]
    y=[]
    for i in range(len(data)-time):
        x.append(data[i:i+time,0])
        y.append(data[i+time,0])
    return np.array(x),np.array(y)

In [8]:
xtrain,ytrain=creat_seq(train_data)
xtest,ytest=creat_seq(test_data)

In [9]:
model=Sequential()

In [10]:
from tensorflow.keras.layers import Dense, LSTM
model.add(LSTM(units=50, return_sequences=True ,input_shape=(6,1)))
model.add(LSTM(units=50))
model.add(Dense(units=1))

In [11]:
model.summary

<bound method Model.summary of <keras.src.engine.sequential.Sequential object at 0x000002CCCBB75A50>>

In [12]:
model.compile(optimizer="adam", loss="mse", metrics=["mae"])

In [13]:
model.fit(xtrain,ytrain,epochs=50)

Epoch 1/50
2/2 [==============================] - 11s 24ms/step - loss: 0.2453 - mae: 0.4585
Epoch 2/50
2/2 [==============================] - 0s 18ms/step - loss: 0.1966 - mae: 0.4078
Epoch 3/50
2/2 [==============================] - 0s 17ms/step - loss: 0.1538 - mae: 0.3557
Epoch 4/50
2/2 [==============================] - 0s 15ms/step - loss: 0.1133 - mae: 0.2970
Epoch 5/50
2/2 [==============================] - 0s 18ms/step - loss: 0.0755 - mae: 0.2366
Epoch 6/50
2/2 [==============================] - 0s 22ms/step - loss: 0.0459 - mae: 0.1842
Epoch 7/50
2/2 [==============================] - 0s 20ms/step - loss: 0.0279 - mae: 0.1445
Epoch 8/50
2/2 [==============================] - 0s 15ms/step - loss: 0.0264 - mae: 0.1230
Epoch 9/50
2/2 [==============================] - 0s 13ms/step - loss: 0.0375 - mae: 0.1401
Epoch 10/50
2/2 [==============================] - 0s 21ms/step - loss: 0.0413 - mae: 0.1497
Epoch 11/50
2/2 [==============================] - 0s 19ms/step - loss: 0.0352

In [14]:
ypred=model.predict(xtest)

1/1 [==============================] - 2s 2s/step


In [15]:
ypred

array([[0.6853195 ],
       [0.68725425],
       [0.7028766 ],
       [0.7259701 ],
       [0.7530804 ],
       [0.7758808 ],
       [0.79532   ]], dtype=float32)

In [16]:
ypred=scaler.inverse_transform(ypred)

In [17]:
ypred

array([[826.85114],
       [827.0065 ],
       [828.2609 ],
       [830.1154 ],
       [832.29236],
       [834.1232 ],
       [835.68414]], dtype=float32)